mazarini_paginator:
    display_one_page: false
    all_pages_limit: 9
    pages_number_count: 3
    per_page: 10
    controller:
#        'App\Entity\Entity':
#            display_one_page: false
#            all_pages_limit: 9
#            page_number_count: 3
#            per_page: 10
#        'App\Entity\EntityInterface':
#            per_page: 4
