mazarini_paginator:
    pager:
        display_previous_next: false
        display_one_page: false
        all_pages_limit: 9
        pages_number_count: 3
        per_page: 10
    class:
        common: 'page-item'
        current: 'active'
        disable: 'disabled'
    label:
        first: '<i class="bi bi-skip-start-fill"></i>'
        previous: '<i class="bi bi-caret-left-fill"></i>'
        next: '<i class="bi bi-caret-right-fill"></i>'
        last: '<i class="bi bi-skip-end-fill"></i>'
